### ISSUE TITLE
issue building with ninja

### ISSUE THREAD

**Issue by gsemonis** [cudawarped/opencv-experiments#2]
Great instructions, but when i try to install with ninja, I get an errror unknown target type 'install'. What worked for me was instead of
cmake --build . --target INSTALL 
was
ninja
ninja install. Ninja is in my current path

**Comment by cudawarped** [comment]
> Great instructions, but when i try to install with ninja, I get an errror unknown target type 'install'. What worked for me was instead of
> cmake --build . --target INSTALL

Thank you I may update the guide to mention the alternative methods for kicking off the build.  That said the above command is incorrect and will result in 
`ninja: error: unknown target 'INSTALL'`
because INSTALL should be lower case.  If you try `ninja INSTALL`  you will get the same error.

Both
```
cmake --build . --target install
ninja install
```
will work when you are inside the build directory, you can check the [CMake documentation ](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Getting%20Started.html#building-your-project) for more details.

There are numerous ways to initiate the build and install process, I chose what I think is the easiest and most consistent method, i.e. both the configuration/generation and build process are kicked off with
`"C:\Program Files\CMake\bin\cmake.exe"`
and everything uses the **PATH_TO_BUILD_DIR** definition.

You could equally call
`ninja -C PATH_TO_BUILD_DIR install`
from any directory on your system.
